/**
 * PWA web app manifest. Lets a rep "Add to Home Screen" on iOS or
 * Android and run PartnerRadar fullscreen as if it were a native app.
 *
 * Next.js 15 file-based metadata: this file generates
 * `/manifest.webmanifest` automatically and Next links to it from
 * every <head>.
 *
 * Theme + colors mirror Storm Cloud's navy / blue palette per SPEC §3.1.
 */

import type { MetadataRoute } from 'next';
import { tenant } from '@partnerradar/config';

export default function manifest(): MetadataRoute.Manifest {
  const t = tenant();
  return {
    name: `${t.brandName} — PartnerRadar`,
    short_name: t.brandName,
    description: `Prospecting CRM for ${t.legalName}`,
    start_url: '/radar',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#0b1220', // matches dark-mode canvas
    theme_color: '#1e40af', // primary blue-800; the URL bar color on Android
    categories: ['business', 'productivity'],
    // Icons are generated by /app/icon.tsx and /app/apple-icon.tsx —
    // Next emits them at the URLs below at build time.
    icons: [
      { src: '/icon.png', sizes: '192x192', type: 'image/png' },
      { src: '/icon.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      { src: '/apple-icon.png', sizes: '180x180', type: 'image/png' },
    ],
  };
}
